### ISSUE TITLE
No access to compile frontend code

### ISSUE THREAD

**Issue by Yolijn** [minvws/nl-rdo-woo-web#14]
### Describe the bug, issue or concern

When following the comprehensive guide to start the project locally I'm having issues at [step 8](https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme#installation).

The [Rijksoverheid Theme](https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme) and the [documentation to add the Github access token](https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme#installation) are not accessible to me as the repository `minvws/nl-rdo-rijksoverheid-ui-theme` is not public.

### To Reproduce
1. Login with a GitHub account that has no access to [https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme](https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme)
2. And with a clean checkout of the `nl-rdo-woo-web` repository
3. Follow the installation guide
4. On [step 8](https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme#installation) see there is no access to the url's
5. And when running the command `docker-compose exec app npm install` regardless, get a `401 Unauthorized` error 

### Expected behavior
To ensure this open source project is actually accessible for developers outside of the `minvws` organisation the theme should also be publicly available. Alternatively the project should not rely on this closed source theme. 

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by JGMichiels** [comment]
Weet dat we bezig zijn om dit voor elkaar te krijgen!

**Comment by sigio** [comment]
It might be possible to use https://github.com/minvws/nl-rdo-manon which is the 'open' variant of the style, however I'm not sure if this is 100% compatible at this time.
