### ISSUE TITLE
No reference to source code from website

### ISSUE THREAD

**Issue by janvlug** [minvws/nl-rdo-woo-web#37]
### Describe the bug, issue or concern

I learned that the website https://open.minvws.nl/ is based on this open source GitHub project.
On the website, I cannot find a reference to this GitHub project.

### To Reproduce
1. Go to https://open.minvws.nl/
2. Try to find a reference to the open source project that provides the website mentioned under 1.

### Expected behavior
A reference to this GitHub project and a mention that the website is based on an open source project.

Maybe this information could me mentioned under "Over deze site".

### Governance
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by annejan** [comment]
We have put a page with information about this github repository, the Code4NL community and used software (for example, tesseract-OCR and Elasticsearch) on our roadmap to be implemented soon.

**Comment by reinschaap** [comment]
We have added a new sentence to the Contact page: https://open.minvws.nl/contact

"De broncode is open source beschikbaar op Github: https://github.com/minvws/nl-rdo-woo-web."
